[workspace]
authors = ["Giordon Stark <kratsg@gmail.com>"]
channels = ["conda-forge"]
name = "af-skills"
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]
pre-commit = { cmd = "pre-commit run --all-files", description = "Run pre-commit hooks on all files" }

[dependencies]
pre-commit = ">=4.5.1,<5"
